# Generated by Django 5.1.7 on 2025-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_download_link_book_image_url_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('novel', 'Novel'), ('biography', 'Biography'), ('science_fiction', 'Science Fiction'), ('poetry', 'Poetry'), ('other', 'Other')], default='novel', max_length=20),
        ),
    ]
