# Generated by Django 5.1.7 on 2025-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_booktype_remove_book_download_link_book_book_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.FileField(blank=True, null=True, upload_to='book_files/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
