# Generated by Django 5.1.7 on 2025-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_book_type_alter_booktype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
